### ISSUE TITLE
search bar functionality

### ISSUE THREAD

**Issue by Aahbree** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#158]
I tried using random characters and digits, I'm getting undesired results at times. The existing functionality states that I should either enter the correct zip code or location else it would throw an error- "Location not found". I'm attaching a screenshot and the link:

https://team2naturescall.herokuapp.com/search_restroom/?csrfmiddlewaretoken=01o7yNR4BAN3CQDMkwxz343nX2ADNiDz57gz7QcebgIv31mCxobTrznncwnfUco5&searched=36th+street+10036+avenue

![team2-tr1.jpg](https://images.zenhubusercontent.com/614ddca82371e5170d31d27f/3ac4ceb1-eaa0-4d96-a52a-0ca1d9b6a5e2)![team2-3.png](https://images.zenhubusercontent.com/614ddca82371e5170d31d27f/ff05f021-1b8b-41ce-b3f5-ebb6c4d0e09a)

Ideas for improvement:
Maybe have a separate search field for zipcode and location the way yelp does.

**Comment by SimonYSC** [comment]
Our search bar is basically the same thing as the location text field of the search bar of Yelp. We don't have the keyword text field like Yelp does because our app is mainly focusing on restroom and won't accept other keywords, such as McDonald's. Thanks for your feedback.
