### ISSUE TITLE
Profile name offers editing field but then does not update

### ISSUE THREAD

**Issue by barksdaleaz** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#160]
**DESCRIPTION OF ISSUE:** 

On the profile page, there is an open/editable textfield for Profilename. I am allowed to type something different in it and click Update, which then takes me to the landing page. However, in the navbar the new username is not updated, and when I go back to the update profile page, the username has also not been changed.

**BUSINESS VALUE:**

Users may initially sign up with a username familiar to them and/or a username that has some identifying information about them (such as their name, or initials, etc). They may then realize they would rather not disclose that they are someone who has gastrointestinal issues/UTI/OAB/diabetes/prostate issues/etc, especially as they start leaving reviews on the profile for other users. They may be worried that someone from their life could see a username on the app that gave away that they were a user, so then they would want to change their username to something more random or anonymous.

**Comment by SimonYSC** [comment]
Fixed
