### ISSUE TITLE
Filtered search without results should show a message indicating there are no results

### ISSUE THREAD

**Issue by barksdaleaz** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#161]
**DESCRIPTION OF ISSUE**:

When searching "Fort Greene" with Accessible & No Transaction Required, there are no results that fit the two filters, so only "Unfiltered Results" appears at the top. There should be some kind of message (at the top, where the filtered results appear) that clarifies that there are simply no restrooms in the area that fit the search.

**BUSINESS VALUE**:

Users may believe that the filters or search feature is not working if they continue to get back unfiltered results - instead of realizing that the unfiltered results are showing simply because there are no restrooms in the area that fit their requirements. This may result in a user wasting time trying to refilter and research again and again hoping to "refresh" the page to see the filtered results. Since the filtered results always appear first, it would be more consistent to have a message at the top to alert the user that there is nothing to be found.

**Comment by SimonYSC** [comment]
This is a good advice. We've made the change. Thanks for the feedback.
