### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by HenryTseTse** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#162]
Not necessarily a bug but when updating a bathroom rating I feel like that updated rating should be now on top of the bathroom ratings page. After I click submit, the first rating I see should be my own. I saw someone else's related and mistakenly thought that it was not updated properly, I had to scroll all the way down on the page just to see it. This can be a problem if you have a large number of ratings and you would not able to check to see if your rating was properly updated. Also I think the map on the bathroom ratings page can be in the a better spot, it's just in the middle of the ratings
<img width="588" alt="Screen Shot 2021-11-18 at 12 22 14 PM" src="https://user-images.githubusercontent.com/33527580/142466960-639be176-8f76-44d6-9295-7a35db3daad5.png">
<img width="1117" alt="Screen Shot 2021-11-18 at 12 27 02 PM" src="https://user-images.githubusercontent.com/33527580/142466962-17779c7d-c261-477a-b384-b8dea99d888d.png">

**Comment by SimonYSC** [comment]
Good advice! However, we've decided that making this change at this point may be too risky for deployment, and we need to move on from this improvement. Thank you for your feedback.
