### ISSUE TITLE
Invalid Email Creation

### ISSUE THREAD

**Issue by HenryTseTse** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#164]
I tried creating an account using an invalid email address, after clicking submit it still informed me that an email was sent. There should be some type of error when trying to create an account with an invalid email address (email address that does not exist). A user can mistype a number or letter in their email address and be waiting all day for that email to come.
<img width="722" alt="Screen Shot 2021-11-18 at 12 48 31 PM" src="https://user-images.githubusercontent.com/33527580/142470566-bbd2276f-3cf9-4e82-8891-35308bfce8f9.png">

**Comment by SimonYSC** [comment]
Comparing to other higher priority tasks, we, the development team, decided not to work on this issue if not having enough time. Thank you for your feedback.
