### ISSUE TITLE
Most of the times, new restroom are not getting added

### ISSUE THREAD

**Issue by Pragdheeshnyu** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#169]
Example case: Search filed 'met'
Gives the MET as the first restaurant and when written any description and clicked on 'Submit' the page doesn't redirect and the restroom is not added.

**Comment by Pragdheeshnyu** [comment]
Upon checking, the restaurants which were manually added (like the ones which have the address ending with a number) we can add a new restroom but for ones that are fetched from Google (like the ones with address ending in random characters), new restrooms cannot be added.

**Comment by ajk8710** [comment]
Hi, could you upload any screenshot about what you are describing?  I did not get what you mean.

**Comment by SimonYSC** [comment]
This is due to the hidden restriction of 10 character limit of the description, which has been lifted. Thanks for the feedback.
