### ISSUE TITLE
Incorrect page redirection when adding new restrooms

### ISSUE THREAD

**Issue by jl12182** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#170]
Steps to reproduce the issue:
1. search for prospect park;
2. select Smorgasburg - Prospect Park Breeze Hill
3. add a new restroom with some description

Unable to add new restroom and page will not be redirected

**Comment by SimonYSC** [comment]
This is due to the hidden restriction of 10 character limit of the description, which has been lifted. Thanks for the feedback.
