### ISSUE TITLE
can access the login/signup page while logged in 

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#172]
Reproduce:
1. Login your user
2. Hardcode:
3.  https://team2naturescall.herokuapp.com/accounts/login
4. https://team2naturescall.herokuapp.com/accounts/signup

You can still see and access the login/signup page

**Comment by SimonYSC** [comment]
Our team think that this is an acceptable User Experience issue instead of a must fix bug, and we decided not to fix it. Thank you for your feedback.
