### ISSUE TITLE
Map on search page pulls up a pinpoint in Oklahoma, and something unlinked to the results on left

### ISSUE THREAD

**Issue by induramesh** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#176]
![Screen Shot 2021-11-19 at 12.10.29 PM.png](https://images.zenhubusercontent.com/614ca547e76e697c7b447148/af4e96e7-ef24-440d-8fed-559b0cbfc348)

(I searched for "Tandon")

The map pulls up a point in Oklahoma, which shouldn't be there....

Also the only results I'm getting are unfiltered, but I do get a green restroom in the New York area, but there is no way for me to be able to tell where/what it is (seems unlinked to the results on the left).

**Comment by SimonYSC** [comment]
This bug has been fixed. Thanks for the feedback.
