### ISSUE TITLE
Rating added message displayed when adding redundant ratings and reviews

### ISSUE THREAD

**Issue by azraf-a** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#177]
DESCRIPTION:
While multiple ratings are still prevented, the page still displays a message saying that a rating has been added when a user adds a second or third review etc.

<img width="936" alt="natures_call_bug1" src="https://user-images.githubusercontent.com/69122096/142689258-af5e74c4-d277-4a59-8768-3f0299426970.PNG">

**Comment by SimonYSC** [comment]
Fixed
