### ISSUE TITLE
Limited Search Results

### ISSUE THREAD

**Issue by azraf-a** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#178]
Description:
For neighborhoods out in Brooklyn or Queens, the results seem overtly limited. I am unsure if this is due to search tuning is happening in the background or if data in the outer boroughs is limited. Attached is a busy street out in BedStuy with only 1 venue displayed; 321 Putnam Avenue was searched in case you want to reproduce.

<img width="950" alt="bug2" src="https://user-images.githubusercontent.com/69122096/142689639-c6faeb09-88fc-49cd-9ae6-06efeb37846b.PNG">
.

**Comment by SimonYSC** [comment]
The team tested several different radius options and find that 500 meter yields the best results, being accessible and relatable. As the result, we will move on to other issues and leave this one as it is. Thank you for your feedback.
