### ISSUE TITLE
[Suggestion] Add more description

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#180]
For the users, when they search for restrooms, it may be counterintuitive to see all restrooms being "Add Restroom".
(They came into see what restrooms to use, and they seem to show restrooms, but no details can be seen.)

Maybe add more description like... "Is there a restroom here? Please add the restroom, you can share the details with others!"

![image](https://user-images.githubusercontent.com/60978943/142698800-367b519b-b0a0-4f25-aa19-e2e796e33529.png)

**Comment by SimonYSC** [comment]
The improvement has been made. Thanks for your feedback.
