### ISSUE TITLE
[Bug] Able to see details page without logging in

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#181]
1. save the url when logged in
2. log out
3. paste the saved url onto the search bar

![image](https://user-images.githubusercontent.com/60978943/142699025-5d9bbd2d-f4df-4007-8463-1693ca1fbbd7.png)

**Comment by SimonYSC** [comment]
This is intended.
Viewing restroom detail does not require user login.

**Comment by SimonYSC** [comment]
Thanks for the feedback, and sorry for the confusion.
