### ISSUE TITLE
Bug/Recommendation: restroom addition and view

### ISSUE THREAD

**Issue by wanghaox2020** [gcivil-nyu-org/Team_Team2_CS-GY-6063-Fall2021#182]
Bug: As an anonymous user, it is unable to zoom in or zoom out according to the location, it gives an anonymous user harder to see the specific location while they use it. 

Recommendation: As I register a new user, I could find a restroom and add it, but the added restroom is not showing on my profile or anywhere I could access it, please set up a view of the added restrooms in the profile or the front pages.

**Comment by SimonYSC** [comment]
The map in the search result page is static, which means it's meant to be non_zoomable, and it's basically a picture. A dynamic map will be accessible in the detail page, which you can zoom in/out and navigate yourself to the restroom you choose.
Secondly, the "Add Restroom" functionality is different from "Favorite" or "Bookmark" functionality, it merely means to create an entry of that restroom in our own database, therefore you won't be able to see it in your profile. To see it listed in your profile, you may give that restroom a rating and comment, which will show in the list in your profile page.
